name: Deploy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest ../backend
        working-directory: ./backend

      - name: Push backend Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest ../frontend
        working-directory: ./frontend

      - name: Push frontend Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_KEY }}" ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            docker-compose -f ../docker-compose.yaml pull
            docker-compose -f ../docker-compose.yaml up -d
          EOF
        env:
          DOCKER_COMPOSE_VERSION: 1.29.2
